In [33]:
import numpy as np
a = np.array([[0, 1], [2, 3], [4, 5], [6, 7]])
b = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

c = np.dot(a, b)
print(c)
c.max()

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]
 [28 41 54 67]]


67